apiVersion: v1
kind: Pod
metadata:
  name: neo4j-dev
  labels:
    app: neo4j-dev
  namespace: fhir-redhat
spec:
  containers:
    - name: neo4j-dev
      image: 'neo4j:latest'
      ports:
        - containerPort: 7473
          protocol: TCP
        - containerPort: 7474
          protocol: TCP
        - containerPort: 7687
          protocol: TCP
      imagePullPolicy: Always
      env:
        - name: NEO4J_server_config_strict__validation_enabled
          value: "false"